export const verdicts = {
  IN_QUEUE: {
    id: 1,
    name: 'IN_QUEUE',
    shortName: 'IQ',
    description: 'In queue',
    color: '#fff',
  },
  PROCESSING: {
    id: 2,
    name: 'PROCESSING',
    shortName: 'P',
    description: 'Processing...',
    color: '#fff',
  },
  ACCEPTED: {
    id: 3,
    name: 'ACCEPTED',
    shortName: 'AC',
    description: 'Accepted',
    color: '#4CAF50',
  },
  WRONG_ANSWER: {
    id: 4,
    name: 'WRONG_ANSWER',
    shortName: 'WA',
    description: 'Wrong answer',
    color: '#F44336',
  },
  TIME_LIMIT_EXCEEDED: {
    id: 5,
    name: 'TIME_LIMIT_EXCEEDED',
    shortName: 'TLE',
    description: 'Time limit exceeded',
    color: '#FF9800',
  },
  COMPILATION_ERROR: {
    id: 6,
    name: 'COMPILATION_ERROR',
    shortName: 'CE',
    description: 'Compilation error',
    color: '#607D8B',
  },
  RUNTIME_ERROR: {
    id: 7,
    name: 'RUNTIME_ERROR',
    shortName: 'RE',
    description: 'Runtime error',
    color: '#B71C1C',
  },
  MEMORY_LIMIT_EXCEEDED: {
    id: 8,
    name: 'MEMORY_LIMIT_EXCEEDED',
    shortName: 'MLE',
    description: 'Memory limit exceeded',
    color: '#FFC107',
  },
  RETURN_ERROR: {
    id: 9,
    name: 'RETURN_ERROR',
    shortName: 'RTE',
    description: 'Return error',
    color: '#673AB7',
  },
  INVALID_RETURN: {
    id: 10,
    name: 'INVALID_RETURN',
    shortName: 'IR',
    description: 'Invalid return',
    color: '#9C27B0',
  },
} as const;
