/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthedAdminRouteImport } from './routes/_authed/_admin'
import { Route as AuthedSubmissionsIndexRouteImport } from './routes/_authed/submissions.index'
import { Route as AuthedProfileIndexRouteImport } from './routes/_authed/profile.index'
import { Route as AuthedLeaderboardIndexRouteImport } from './routes/_authed/leaderboard.index'
import { Route as AuthedGroupsIndexRouteImport } from './routes/_authed/groups/index'
import { Route as AuthedExercisesIndexRouteImport } from './routes/_authed/exercises/index'
import { Route as AuthedGroupsGroupIdRouteImport } from './routes/_authed/groups/$groupId'
import { Route as AuthedGroupsGroupIdIndexRouteImport } from './routes/_authed/groups/$groupId/index'
import { Route as AuthedExercisesExerciseIdIndexRouteImport } from './routes/_authed/exercises/$exerciseId.index'
import { Route as AuthedAdminTopicsIndexRouteImport } from './routes/_authed/_admin/topics.index'
import { Route as AuthedGroupsGroupIdStudentsIndexRouteImport } from './routes/_authed/groups/$groupId/students.index'
import { Route as AuthedGroupsGroupIdExercisesIndexRouteImport } from './routes/_authed/groups/$groupId/exercises.index'
import { Route as AuthedGroupsGroupIdDashboardIndexRouteImport } from './routes/_authed/groups/$groupId/dashboard.index'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSubmissionsIndexRoute = AuthedSubmissionsIndexRouteImport.update({
  id: '/submissions/',
  path: '/submissions/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfileIndexRoute = AuthedProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLeaderboardIndexRoute = AuthedLeaderboardIndexRouteImport.update({
  id: '/leaderboard/',
  path: '/leaderboard/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGroupsIndexRoute = AuthedGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedExercisesIndexRoute = AuthedExercisesIndexRouteImport.update({
  id: '/exercises/',
  path: '/exercises/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGroupsGroupIdRoute = AuthedGroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGroupsGroupIdIndexRoute =
  AuthedGroupsGroupIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedGroupsGroupIdRoute,
  } as any)
const AuthedExercisesExerciseIdIndexRoute =
  AuthedExercisesExerciseIdIndexRouteImport.update({
    id: '/exercises/$exerciseId/',
    path: '/exercises/$exerciseId/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAdminTopicsIndexRoute = AuthedAdminTopicsIndexRouteImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedGroupsGroupIdStudentsIndexRoute =
  AuthedGroupsGroupIdStudentsIndexRouteImport.update({
    id: '/students/',
    path: '/students/',
    getParentRoute: () => AuthedGroupsGroupIdRoute,
  } as any)
const AuthedGroupsGroupIdExercisesIndexRoute =
  AuthedGroupsGroupIdExercisesIndexRouteImport.update({
    id: '/exercises/',
    path: '/exercises/',
    getParentRoute: () => AuthedGroupsGroupIdRoute,
  } as any)
const AuthedGroupsGroupIdDashboardIndexRoute =
  AuthedGroupsGroupIdDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthedGroupsGroupIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/': typeof AuthedIndexRoute
  '/groups/$groupId': typeof AuthedGroupsGroupIdRouteWithChildren
  '/exercises': typeof AuthedExercisesIndexRoute
  '/groups': typeof AuthedGroupsIndexRoute
  '/leaderboard': typeof AuthedLeaderboardIndexRoute
  '/profile': typeof AuthedProfileIndexRoute
  '/submissions': typeof AuthedSubmissionsIndexRoute
  '/topics': typeof AuthedAdminTopicsIndexRoute
  '/exercises/$exerciseId': typeof AuthedExercisesExerciseIdIndexRoute
  '/groups/$groupId/': typeof AuthedGroupsGroupIdIndexRoute
  '/groups/$groupId/dashboard': typeof AuthedGroupsGroupIdDashboardIndexRoute
  '/groups/$groupId/exercises': typeof AuthedGroupsGroupIdExercisesIndexRoute
  '/groups/$groupId/students': typeof AuthedGroupsGroupIdStudentsIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/': typeof AuthedIndexRoute
  '/exercises': typeof AuthedExercisesIndexRoute
  '/groups': typeof AuthedGroupsIndexRoute
  '/leaderboard': typeof AuthedLeaderboardIndexRoute
  '/profile': typeof AuthedProfileIndexRoute
  '/submissions': typeof AuthedSubmissionsIndexRoute
  '/topics': typeof AuthedAdminTopicsIndexRoute
  '/exercises/$exerciseId': typeof AuthedExercisesExerciseIdIndexRoute
  '/groups/$groupId': typeof AuthedGroupsGroupIdIndexRoute
  '/groups/$groupId/dashboard': typeof AuthedGroupsGroupIdDashboardIndexRoute
  '/groups/$groupId/exercises': typeof AuthedGroupsGroupIdExercisesIndexRoute
  '/groups/$groupId/students': typeof AuthedGroupsGroupIdStudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authed/_admin': typeof AuthedAdminRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/groups/$groupId': typeof AuthedGroupsGroupIdRouteWithChildren
  '/_authed/exercises/': typeof AuthedExercisesIndexRoute
  '/_authed/groups/': typeof AuthedGroupsIndexRoute
  '/_authed/leaderboard/': typeof AuthedLeaderboardIndexRoute
  '/_authed/profile/': typeof AuthedProfileIndexRoute
  '/_authed/submissions/': typeof AuthedSubmissionsIndexRoute
  '/_authed/_admin/topics/': typeof AuthedAdminTopicsIndexRoute
  '/_authed/exercises/$exerciseId/': typeof AuthedExercisesExerciseIdIndexRoute
  '/_authed/groups/$groupId/': typeof AuthedGroupsGroupIdIndexRoute
  '/_authed/groups/$groupId/dashboard/': typeof AuthedGroupsGroupIdDashboardIndexRoute
  '/_authed/groups/$groupId/exercises/': typeof AuthedGroupsGroupIdExercisesIndexRoute
  '/_authed/groups/$groupId/students/': typeof AuthedGroupsGroupIdStudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/auth/login'
    | '/'
    | '/groups/$groupId'
    | '/exercises'
    | '/groups'
    | '/leaderboard'
    | '/profile'
    | '/submissions'
    | '/topics'
    | '/exercises/$exerciseId'
    | '/groups/$groupId/'
    | '/groups/$groupId/dashboard'
    | '/groups/$groupId/exercises'
    | '/groups/$groupId/students'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/auth/login'
    | '/'
    | '/exercises'
    | '/groups'
    | '/leaderboard'
    | '/profile'
    | '/submissions'
    | '/topics'
    | '/exercises/$exerciseId'
    | '/groups/$groupId'
    | '/groups/$groupId/dashboard'
    | '/groups/$groupId/exercises'
    | '/groups/$groupId/students'
  id:
    | '__root__'
    | '/_authed'
    | '/auth'
    | '/_authed/_admin'
    | '/auth/login'
    | '/_authed/'
    | '/_authed/groups/$groupId'
    | '/_authed/exercises/'
    | '/_authed/groups/'
    | '/_authed/leaderboard/'
    | '/_authed/profile/'
    | '/_authed/submissions/'
    | '/_authed/_admin/topics/'
    | '/_authed/exercises/$exerciseId/'
    | '/_authed/groups/$groupId/'
    | '/_authed/groups/$groupId/dashboard/'
    | '/_authed/groups/$groupId/exercises/'
    | '/_authed/groups/$groupId/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authed/_admin': {
      id: '/_authed/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/submissions/': {
      id: '/_authed/submissions/'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof AuthedSubmissionsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profile/': {
      id: '/_authed/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/leaderboard/': {
      id: '/_authed/leaderboard/'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthedLeaderboardIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/groups/': {
      id: '/_authed/groups/'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthedGroupsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/exercises/': {
      id: '/_authed/exercises/'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof AuthedExercisesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/groups/$groupId': {
      id: '/_authed/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof AuthedGroupsGroupIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/groups/$groupId/': {
      id: '/_authed/groups/$groupId/'
      path: '/'
      fullPath: '/groups/$groupId/'
      preLoaderRoute: typeof AuthedGroupsGroupIdIndexRouteImport
      parentRoute: typeof AuthedGroupsGroupIdRoute
    }
    '/_authed/exercises/$exerciseId/': {
      id: '/_authed/exercises/$exerciseId/'
      path: '/exercises/$exerciseId'
      fullPath: '/exercises/$exerciseId'
      preLoaderRoute: typeof AuthedExercisesExerciseIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_admin/topics/': {
      id: '/_authed/_admin/topics/'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof AuthedAdminTopicsIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/groups/$groupId/students/': {
      id: '/_authed/groups/$groupId/students/'
      path: '/students'
      fullPath: '/groups/$groupId/students'
      preLoaderRoute: typeof AuthedGroupsGroupIdStudentsIndexRouteImport
      parentRoute: typeof AuthedGroupsGroupIdRoute
    }
    '/_authed/groups/$groupId/exercises/': {
      id: '/_authed/groups/$groupId/exercises/'
      path: '/exercises'
      fullPath: '/groups/$groupId/exercises'
      preLoaderRoute: typeof AuthedGroupsGroupIdExercisesIndexRouteImport
      parentRoute: typeof AuthedGroupsGroupIdRoute
    }
    '/_authed/groups/$groupId/dashboard/': {
      id: '/_authed/groups/$groupId/dashboard/'
      path: '/dashboard'
      fullPath: '/groups/$groupId/dashboard'
      preLoaderRoute: typeof AuthedGroupsGroupIdDashboardIndexRouteImport
      parentRoute: typeof AuthedGroupsGroupIdRoute
    }
  }
}

interface AuthedAdminRouteChildren {
  AuthedAdminTopicsIndexRoute: typeof AuthedAdminTopicsIndexRoute
}

const AuthedAdminRouteChildren: AuthedAdminRouteChildren = {
  AuthedAdminTopicsIndexRoute: AuthedAdminTopicsIndexRoute,
}

const AuthedAdminRouteWithChildren = AuthedAdminRoute._addFileChildren(
  AuthedAdminRouteChildren,
)

interface AuthedGroupsGroupIdRouteChildren {
  AuthedGroupsGroupIdIndexRoute: typeof AuthedGroupsGroupIdIndexRoute
  AuthedGroupsGroupIdDashboardIndexRoute: typeof AuthedGroupsGroupIdDashboardIndexRoute
  AuthedGroupsGroupIdExercisesIndexRoute: typeof AuthedGroupsGroupIdExercisesIndexRoute
  AuthedGroupsGroupIdStudentsIndexRoute: typeof AuthedGroupsGroupIdStudentsIndexRoute
}

const AuthedGroupsGroupIdRouteChildren: AuthedGroupsGroupIdRouteChildren = {
  AuthedGroupsGroupIdIndexRoute: AuthedGroupsGroupIdIndexRoute,
  AuthedGroupsGroupIdDashboardIndexRoute:
    AuthedGroupsGroupIdDashboardIndexRoute,
  AuthedGroupsGroupIdExercisesIndexRoute:
    AuthedGroupsGroupIdExercisesIndexRoute,
  AuthedGroupsGroupIdStudentsIndexRoute: AuthedGroupsGroupIdStudentsIndexRoute,
}

const AuthedGroupsGroupIdRouteWithChildren =
  AuthedGroupsGroupIdRoute._addFileChildren(AuthedGroupsGroupIdRouteChildren)

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRouteWithChildren
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedGroupsGroupIdRoute: typeof AuthedGroupsGroupIdRouteWithChildren
  AuthedExercisesIndexRoute: typeof AuthedExercisesIndexRoute
  AuthedGroupsIndexRoute: typeof AuthedGroupsIndexRoute
  AuthedLeaderboardIndexRoute: typeof AuthedLeaderboardIndexRoute
  AuthedProfileIndexRoute: typeof AuthedProfileIndexRoute
  AuthedSubmissionsIndexRoute: typeof AuthedSubmissionsIndexRoute
  AuthedExercisesExerciseIdIndexRoute: typeof AuthedExercisesExerciseIdIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRouteWithChildren,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedGroupsGroupIdRoute: AuthedGroupsGroupIdRouteWithChildren,
  AuthedExercisesIndexRoute: AuthedExercisesIndexRoute,
  AuthedGroupsIndexRoute: AuthedGroupsIndexRoute,
  AuthedLeaderboardIndexRoute: AuthedLeaderboardIndexRoute,
  AuthedProfileIndexRoute: AuthedProfileIndexRoute,
  AuthedSubmissionsIndexRoute: AuthedSubmissionsIndexRoute,
  AuthedExercisesExerciseIdIndexRoute: AuthedExercisesExerciseIdIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
