/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthedSubmissionsIndexRouteImport } from './routes/_authed/submissions.index'
import { Route as AuthedProfileIndexRouteImport } from './routes/_authed/profile.index'
import { Route as AuthedLeaderboardIndexRouteImport } from './routes/_authed/leaderboard.index'
import { Route as AuthedGroupsIndexRouteImport } from './routes/_authed/groups.index'
import { Route as AuthedExercisesIndexRouteImport } from './routes/_authed/exercises/index'
import { Route as AuthedExercisesExerciseIdIndexRouteImport } from './routes/_authed/exercises/$exerciseId.index'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthedSubmissionsIndexRoute = AuthedSubmissionsIndexRouteImport.update({
  id: '/submissions/',
  path: '/submissions/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfileIndexRoute = AuthedProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLeaderboardIndexRoute = AuthedLeaderboardIndexRouteImport.update({
  id: '/leaderboard/',
  path: '/leaderboard/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGroupsIndexRoute = AuthedGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedExercisesIndexRoute = AuthedExercisesIndexRouteImport.update({
  id: '/exercises/',
  path: '/exercises/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedExercisesExerciseIdIndexRoute =
  AuthedExercisesExerciseIdIndexRouteImport.update({
    id: '/exercises/$exerciseId/',
    path: '/exercises/$exerciseId/',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/': typeof AuthedIndexRoute
  '/exercises': typeof AuthedExercisesIndexRoute
  '/groups': typeof AuthedGroupsIndexRoute
  '/leaderboard': typeof AuthedLeaderboardIndexRoute
  '/profile': typeof AuthedProfileIndexRoute
  '/submissions': typeof AuthedSubmissionsIndexRoute
  '/exercises/$exerciseId': typeof AuthedExercisesExerciseIdIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/': typeof AuthedIndexRoute
  '/exercises': typeof AuthedExercisesIndexRoute
  '/groups': typeof AuthedGroupsIndexRoute
  '/leaderboard': typeof AuthedLeaderboardIndexRoute
  '/profile': typeof AuthedProfileIndexRoute
  '/submissions': typeof AuthedSubmissionsIndexRoute
  '/exercises/$exerciseId': typeof AuthedExercisesExerciseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/exercises/': typeof AuthedExercisesIndexRoute
  '/_authed/groups/': typeof AuthedGroupsIndexRoute
  '/_authed/leaderboard/': typeof AuthedLeaderboardIndexRoute
  '/_authed/profile/': typeof AuthedProfileIndexRoute
  '/_authed/submissions/': typeof AuthedSubmissionsIndexRoute
  '/_authed/exercises/$exerciseId/': typeof AuthedExercisesExerciseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/auth/login'
    | '/auth/register'
    | '/'
    | '/exercises'
    | '/groups'
    | '/leaderboard'
    | '/profile'
    | '/submissions'
    | '/exercises/$exerciseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/auth/login'
    | '/auth/register'
    | '/'
    | '/exercises'
    | '/groups'
    | '/leaderboard'
    | '/profile'
    | '/submissions'
    | '/exercises/$exerciseId'
  id:
    | '__root__'
    | '/_authed'
    | '/auth'
    | '/auth/login'
    | '/auth/register'
    | '/_authed/'
    | '/_authed/exercises/'
    | '/_authed/groups/'
    | '/_authed/leaderboard/'
    | '/_authed/profile/'
    | '/_authed/submissions/'
    | '/_authed/exercises/$exerciseId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authed/submissions/': {
      id: '/_authed/submissions/'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof AuthedSubmissionsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profile/': {
      id: '/_authed/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/leaderboard/': {
      id: '/_authed/leaderboard/'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthedLeaderboardIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/groups/': {
      id: '/_authed/groups/'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthedGroupsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/exercises/': {
      id: '/_authed/exercises/'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof AuthedExercisesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/exercises/$exerciseId/': {
      id: '/_authed/exercises/$exerciseId/'
      path: '/exercises/$exerciseId'
      fullPath: '/exercises/$exerciseId'
      preLoaderRoute: typeof AuthedExercisesExerciseIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedExercisesIndexRoute: typeof AuthedExercisesIndexRoute
  AuthedGroupsIndexRoute: typeof AuthedGroupsIndexRoute
  AuthedLeaderboardIndexRoute: typeof AuthedLeaderboardIndexRoute
  AuthedProfileIndexRoute: typeof AuthedProfileIndexRoute
  AuthedSubmissionsIndexRoute: typeof AuthedSubmissionsIndexRoute
  AuthedExercisesExerciseIdIndexRoute: typeof AuthedExercisesExerciseIdIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedExercisesIndexRoute: AuthedExercisesIndexRoute,
  AuthedGroupsIndexRoute: AuthedGroupsIndexRoute,
  AuthedLeaderboardIndexRoute: AuthedLeaderboardIndexRoute,
  AuthedProfileIndexRoute: AuthedProfileIndexRoute,
  AuthedSubmissionsIndexRoute: AuthedSubmissionsIndexRoute,
  AuthedExercisesExerciseIdIndexRoute: AuthedExercisesExerciseIdIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
